language: golang

go:
  - 1.4

env:
  global:
  - GOPATH="$HOME/gopath"
  - PATH="$HOME/gopath/bin:$HOME/bin:$PATH"


install:
  - go get github.com/stretchr/testify/assert
  - go get github.com/vanng822/r2router

script:
  - go test -v
